version: "3.8"

services:
  face-attendance:
    build: .
    container_name: tgmt-face-attendance
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./exports:/app/exports
      - ./attendance_system.db:/app/attendance_system.db
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add Nginx as reverse proxy
  nginx:
    image: nginx:alpine
    container_name: tgmt-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro # Mount SSL certificates if available
    depends_on:
      - face-attendance
    restart: unless-stopped
    profiles:
      - nginx # Use 'docker-compose --profile nginx up' to include nginx
