version: "3.8"

services:
  face-attendance:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: tgmt-face-attendance-simple
    ports:
      - "5000:5000"
      - "80:5000" # Also bind to port 80 for easier access
    volumes:
      - ./uploads:/app/uploads
      - ./exports:/app/exports
      - ./attendance_system.db:/app/attendance_system.db
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
      - HOST=0.0.0.0 # Bind to all interfaces
      - PORT=5000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - tgmt-network

networks:
  tgmt-network:
    driver: bridge
