# Render.yaml - FORCE PYTHON 3.10 Configuration
services:
  - type: web
    name: tgmt-face-attendance
    env: docker
    dockerfilePath: ./Dockerfile.render
    plan: free
    region: singapore
    branch: main
    # Force rebuild with new settings
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 5000
      - key: PYTHONUNBUFFERED
        value: 1
      - key: FORCE_PYTHON_310
        value: true
    buildFilter:
      paths:
        - "**"
      ignoredPaths:
        - "README.md"
        - "*.md"
        - ".git/**"
