# Render.yaml - Configuration for Render.com deployment
services:
  - type: web
    name: tgmt-face-attendance
    env: docker
    dockerfilePath: ./Dockerfile.render
    plan: free
    region: singapore
    branch: main
    # healthCheckPath: /health  # Disabled temporarily for debugging
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 5000
      - key: PYTHONUNBUFFERED
        value: 1
    buildFilter:
      paths:
        - "**"
      ignoredPaths:
        - "README.md"
        - "*.md"
        - ".git/**"
